Boys = 8
Boys += 8
print(f"BOYS ARE {Boys}")
Boys = 8
Boys -= 8
print(f"BOYS ARE {Boys}")
Boys = 8
Boys *= 8
print(f"BOYS ARE {Boys}")
Boys = 8
Boys /= 8
print(f"BOYS ARE {Boys}")
Boys = 8
Boys //= 8
print(f"BOYS ARE {Boys}")
Boys = 8
Boys %= 8
print(f"BOYS ARE {Boys}")